### PR TITLE
Bump Envoy version: a82962c

### PR DESCRIPTION
**Pull request by Augustyniak**
Picking up the following changes https://github.com/envoyproxy/envoy/compare/57bfbda2a50d2f026cf64c82383fe3bebe1e0860...a82962cebd26d04637284e9b04e6f32ad49cbe12

There was an error:
```
external/envoy/source/common/buffer/watermark_buffer.cc:5:10: fatal error: 'absl/numeric/bits.h' file not found
#include "absl/numeric/bits.h"
```
which we were able to get rid of by updating `com_google_absl` dependency.

Description:
Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Review by buildbreaker — DISMISSED** [review]
Thanks @Augustyniak !

**Comment by goaway** [comment]
Thanks @Augustyniak and @snowp!

**Review by goaway — DISMISSED** [review]

**Comment by ulfjack** [comment]
FYI: The failure of `ios_build_shadow` was caused by me making a change to the CI. Please ignore.

**Comment by goaway** [comment]
🤞

**Comment by Augustyniak** [comment]
I need to update Envoy again since the current version of Envoy makes iOS/Android hello world application crash:
```
[2021-08-06 15:39:47.049][1052159][critical][assert] [external/envoy/source/server/proto_descriptors.cc:49] assert failure: Protobuf::DescriptorPool::generated_pool()->FindMessageTypeByName(type) != nullptr. Details: envoy.api.v2.Cluster
```

Envoy issues were fixed in upstream Envoy as part of https://github.com/envoyproxy/envoy/pull/17622.

**Review by goaway — APPROVED** [review]
Thanks @Augustyniak!

**Comment by Augustyniak** [comment]
Just a note about why we needed to add new linker flags as part of this PR.

We needed to add:
```
build:clang-asan --linkopt --rtlib=compiler-rt
build:clang-asan --linkopt --unwindlib=libgcc
```

since without these additional asan job was failing with the following error:
```
Execution platform: @local_config_platform//:host
ld.lld: error: undefined symbol: __muloti4
>>> referenced by numbers.cc
>>>               bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/strings/_objs/strings/numbers.pic.o:(absl::operator*(absl::int128, absl::int128))
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Pull request merged**
