### PR TITLE
[DO NOT MERGE] Moving endpoint for running CI jobs in new EngFlow cluster

### PR DESCRIPTION
**Pull request by anfelbar**
Description: Engflow is making some internal changes to make the infrastructure more scalable and that requires using a new endpoint. This PR runs all necessary CI jobs in the new cluster. We have made some dns changes that are propagation now. Even without the propagation of dns, if this PR is approved then the cluster endpoint gets updated and the build can continue on the new cluster (each branch should merge the master branch). 
Risk Level: Medium
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
[Optional Fixes #Issue]
[Optional Deprecated:]

Signed-off-by: Andrés Felipe Barco Santa <andres@engflow.com>

### CODE REVIEW

**Comment by anfelbar** [comment]
@lfpino I need a review for this.

**Comment by anfelbar** [comment]
@lfpino we are ready to move to the new cluster.
docs are failing in the circleci but not in our cluster.

**Comment by anfelbar** [comment]
We have made some dns changes that are propagation now. Even without the propagation of dns, if this PR is approved then the cluster endpoint gets updated and the build can continue on the new cluster (each branch should merge the master branch).

**Comment by lfpino** [comment]
Some of the workflows are failing, can you look into that?

@jpsim could you please review this?

**Comment by jpsim** [comment]
> could you please review this?

What are you suggesting I review? I don't see any changes in this branch.

image

**Comment by anfelbar** [comment]
> > could you please review this?
> 
> What are you suggesting I review? I don't see any changes in this branch.
> 
> image

@jpsim actually we just changed DNS as to be able to work with the same envoy.cluster.engflow.com endpoint (that now points to the new modularized cluster). The only thing remaining is to test releases that are not triggered by the normal PR. Is it possible for you to trigger the releases building process? Once we know that part is working then we can close this PR without merging it. This is the last step.

**Comment by jpsim** [comment]
> The only thing remaining is to test releases that are not triggered by the normal PR. Is it possible for you to trigger the releases building process?

Running the release jobs now: https://github.com/envoyproxy/envoy-mobile/actions/runs/3128074078

The previous run failed yesterday with SSL errors: https://github.com/envoyproxy/envoy-mobile/actions/runs/3128074078/jobs/5075452741

**Comment by jpsim** [comment]
The release jobs passed: https://github.com/envoyproxy/envoy-mobile/actions/runs/3128074078

**Comment by anfelbar** [comment]
> The release jobs passed: https://github.com/envoyproxy/envoy-mobile/actions/runs/3128074078

Wonderful. So right now the migration is complete and the same endpoint envoy.cluster.engflow.com is used. I'm closing this testing PR. Thank you @jpsim and @lfpino 

> > The only thing remaining is to test releases that are not triggered by the normal PR. Is it possible for you to trigger the releases building process?
> 
> Running the release jobs now: https://github.com/envoyproxy/envoy-mobile/actions/runs/3128074078
> 
> The previous run failed yesterday with SSL errors: https://github.com/envoyproxy/envoy-mobile/actions/runs/3128074078/jobs/5075452741

Most likely it failed because DNS propagation.

**Comment by anfelbar** [comment]
The new cluster is then in use with the same endpoint envoy.cluster.engflow.com. I am closing this PR. Thank you @jpsim and @lfpino

**Pull request closed without merging**
