### PR TITLE
config: hopefully fixing C++ config default for apple

### PR DESCRIPTION
**Pull request by alyssawilk**
Replacing the default dns resolver in the config string to be correct for the OS in question.
Replaced overrides in the swift code now that the base config handles it.

Risk Level: low
Testing: existing tests should verify correctness
Docs Changes: n/a
Release Notes: did not add

### CODE REVIEW

**Comment by jpsim** [comment]
Can you also remove this line? https://github.com/envoyproxy/envoy-mobile/blob/2ea19b7f8862f8d102750b1e9b95350969eb8c2e/library/objective-c/EnvoyConfiguration.m#L157

**Comment by alyssawilk** [comment]
Good call, thanks!

**Review by jpsim — APPROVED** [review]
Thanks!

**Review by goaway — APPROVED** [review]
Makes sense to me. Longer-term, I can see this being potentially useful to expose through the builder, but not as anything that would need to block this change. Thanks @alyssawilk!

**Pull request merged**
