### PR TITLE
main: fix argc

### PR DESCRIPTION
**Pull request by junr03**
Description: #1338 changed argv, but kept argc the same. This PR updates command line args to no longer depend on a hardcoded value.
Risk Level: low
Testing: local build to make sure all command line args were being respected.

Signed-off-by: Jose Nino <jnino@lyft.com>

### CODE REVIEW

**Review by goaway — APPROVED** [review]
Good catch, thanks!

**Comment by rebello95** [comment]
Does the original PR result in any functional breakage?

**Comment by junr03** [comment]
@rebello95, yeah, changing log levels would not take effect.

**Comment by rebello95** [comment]
Got it. What is the default used by Envoy (what did we end up shipping to production if our overrides do not take effect?)?

**Comment by junr03** [comment]
info should be default

**Pull request merged**
