### PR TITLE
owners: move junr03 to emeritus

### PR DESCRIPTION
**Pull request by junr03**
Signed-off-by: Jose Nino <jnino@lyft.com>

### CODE REVIEW

**Review by alyssawilk — APPROVED** [review]
:-(

**Comment by mattklein123** [comment]
Thank you so much Jose for everything you have done over the years. The project would not be what it is today without. Maybe one day we will see you back. :)

**Comment by jpsim** [comment]
😢 it's been great working with you these last few months, Jose. You'll be missed. Although "maintainer emeritus" is a dope title 😆 

PS: Can you remove yourself from [lyft_maintainers.yml](https://github.com/envoyproxy/envoy-mobile/blob/main/.github/lyft_maintainers.yml) too?

**Comment by junr03** [comment]
Will do in a different PR @jpsim!

**Comment by goaway** [comment]
It's been an amazing journey @junr03. :)

**Pull request merged**
