### PR TITLE
Bump envoy and fix tests for key-value ttl

### PR DESCRIPTION
**Pull request by caschoener**
This addresses https://github.com/envoyproxy/envoy/issues/22303. Most of the code is found in https://github.com/envoyproxy/envoy/pull/22884, this is just fixing up some tests.

### CODE REVIEW

**Comment by jpsim** [comment]
/retest

There were some CI issues yesterday: https://envoyproxy.slack.com/archives/C02QMNG92A3/p1662719745919179

**Comment by caschoener** [comment]
Currently blocked by this error message https://pastebin.com/qX8QbTuf

**Comment by jpsim** [comment]
I might re-apply your commit on top of https://github.com/envoyproxy/envoy-mobile/pull/2540

**Comment by caschoener** [comment]
That would be awesome!  Wasn't sure what the protocol is when builds are failing.

Feel free to ping me if these tests don't succeed, haven't been able to test it in awhile for obvious reasons.

**Comment by caschoener** [comment]
Closed by #2540, I think

**Pull request closed without merging**
