### PR TITLE
[WIP/TESTING] extensions: Update config

### PR DESCRIPTION
**Pull request by phlax**
Description: extensions: Update config
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by phlax** [comment]
@envoyproxy/envoy-mobile-maintainers would you mind allowing CI on this PR - im trying to check if https://github.com/envoyproxy/envoy/pull/16496 will break anything here (almost certainly yes) and what update is required to unbreak it

**Comment by phlax** [comment]
cc @htuch

**Comment by buildbreaker** [comment]
@phlax This is quite strange of a symptom because we do have Actions enabled for you

Let me see if I can get a quick workaround for you so you can be unblocked

**Comment by phlax** [comment]
wierdly - i have just received a load of emails telling me that these jobs have failed - but its still not showing here

i have enough info from the failing jobs to update PR i think

**Comment by buildbreaker** [comment]
@phlax Ok! If that works for you for now, I'll let you continue on

**Comment by goaway** [comment]
@phlax thank you for doing diligence here! Let me know if I can assist.

**Comment by junr03** [comment]
Re-open if needed

**Pull request closed without merging**
