### PR TITLE
Update robolectric-bazel rules from 4.4 -> 4.8.1

### PR DESCRIPTION
**Pull request by Bencodes**
https://github.com/robolectric/robolectric-bazel/releases/tag/4.8.1

Signed-off-by: Benjamin Lee <ben@ben.cm>

### CODE REVIEW

**Comment by snowp** [comment]
@Bencodes Is this still relevant?

**Comment by Augustyniak** [comment]
@Bencodes Any particular reason for this update? Should we merge if it's green?

**Comment by Bencodes** [comment]
@Augustyniak keeping these up to date is always a good idea and I would merge if the status are passing.

**Comment by Augustyniak** [comment]
Closing. Being worked on as a part of a separate PR https://github.com/envoyproxy/envoy-mobile/pull/2565

**Pull request closed without merging**
