### PR TITLE
CI: Move tsan workflow to Engflow's remote execution

### PR DESCRIPTION
**Pull request by lfpino**
Description:
CI: Move tsan workflow to Engflow's remote execution

Same as https://github.com/envoyproxy/envoy-mobile/pull/1745 but using a couple of tsan flags instead of asan. Using a separate config for modularity.

Risk Level: Low
Testing: See tsan workflow
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by lfpino** [comment]
@goaway This is identical to ASAN but with a few different flags. Please take a look

I also cleaned up some redundant flags and once we finish more flows we can see how to unify better the configs.

**Review by goaway — COMMENTED** [review]
Thanks @lfpino! LGTM, pending CI.

**Review by goaway — APPROVED** [review]
And since tsan already passed, looks like this will be good to go when it completes.

**Comment by lfpino** [comment]
I think you can merge now.

**Review by goaway — APPROVED** [review]

**Pull request merged**
