### PR TITLE
ci: enable running of android tests in linux kotlin tests

### PR DESCRIPTION
**Pull request by Augustyniak**
Description: Make it possible to run Android Roboletric tests as part of kotlin linux testsuite.
Risk Level: None, tests only
Testing: N/A
Docs Changes: N/A
Release Notes:  N/A

Signed-off-by: Rafal Augustyniak <raugustyniak@lyft.com>

### CODE REVIEW

**Comment by Augustyniak** [comment]
The change was extracted from https://github.com/envoyproxy/envoy-mobile/pull/2416

**Comment by Augustyniak** [comment]
@snowp should be ready for a re-review

**Review by snowp — APPROVED** [review]

**Pull request merged**
