### PR TITLE
http: adding alpn clusters accessed via x-envoy-mobile-upstream-protocol: alpn

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: low
Testing: unit tests
Docs Changes: n/a
Release Notes: n/a
Part of #1548
Part of #1558

### CODE REVIEW

**Comment by alyssawilk** [comment]
CI failure is legit - please ignore this PR for now :-P

**Comment by goaway** [comment]
Re-running iOS app tests.

**Comment by alyssawilk** [comment]
No, as said over in the propercase PR, I update Envoy to handle propercasing there but had added it to the "prod config" here

Initially I'd had some syntax errors, and the cc tests using config failed.  I'm pretty confident with those passing now this is valid config, but it's _only_ valid config for new Envoy-mobile builds with the propercasing library linked in.

I thought adding propercasing to library/common/config/BUILD would be sufficient but as this is still failing I'm wondering if something in this test uses prebuilt envoy-mobile, and if I have to submit a PR with the new linking rule, then submit a follow-up PR using the new link rule.  Thoughts?

**Comment by alyssawilk** [comment]
ok in the absence of advice I'll try checking in the build changes for preserving case, and see if a follow-up PR applying the config sticks better.

**Review by goaway — APPROVED** [review]
Looks good. Thank you @alyssawilk!

**Pull request merged**
