### PR TITLE
bazel: Add flatbuffers Swift hack

### PR DESCRIPTION
**Pull request by keith**
The generated code couldn't be used with private_deps because it
imported FlatBuffers normally and created a bunch of public types.
Ideally this would be an option to the generator instead of doing this.

This will have to be updated to a loop to support multiple input files

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Review by snowp — APPROVED** [review]
Thanks!

**Review by jpsim — APPROVED** [review]
nice

**Comment by keith** [comment]
> nice

you use this loosely I see

**Comment by jpsim** [comment]
The end result is nice. The hack is not that bad imho in that it is localized and should be relatively easily upstream-able as a configuration as you said.

**Pull request merged**
