### PR TITLE
Use port 0 when starting the stats server in stat_flush_integration_test

### PR DESCRIPTION
**Pull request by RyanTheOptimist**
Signed-off-by: Ryan Hamilton <rch@google.com>

Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by goaway** [comment]
Just wanted to check in on the status here - looks like there's a failing check, though it may be spurious? (I didn't happen to look.) If this is ready for review, feel free to assign to me.

**Comment by snowp** [comment]
@RyanTheOptimist ping, is this still something we want to land?

**Comment by jpsim** [comment]
I believe this was meant to demonstrate that overriding the port isn't actually respected when the configuration is converted to YAML, and that's something that @goaway had volunteered to fix.

**Comment by Augustyniak** [comment]
That issue may become obsolete once https://github.com/envoyproxy/envoy-mobile/pull/2563 is merged.

**Pull request closed without merging**
