### PR TITLE
CI: Re-enable engflow for kotlin tests

### LINKED ISSUE #2020: [CI] Run integration tests on EngFlow
In https://github.com/envoyproxy/envoy-mobile/pull/1995 I disabled remote execution for the integration test CI jobs because of test failures that were only occurring when using remote execution but ran fine on GitHub Actions workers directly.

Here's the kind of failure we were seeing when running these tests with remote execution: https://github.com/envoyproxy/envoy-mobile/runs/4739746396?check_suite_focus=true

And the same tests running successfully without remote execution: https://github.com/envoyproxy/envoy-mobile/runs/4740616118?check_suite_focus=true

### PR DESCRIPTION
**Pull request by lfpino**
Signed-off-by: Luis Fernando Pino Duque <luis@engflow.com>

Description:
Re-enable engflow for kotlin tests by using JDK 8 and allowing pulse_client_impl_test and engine_builder_test to run without a sandbox. Those tests are trying to access a path under "/var/folders/wp/..." as part of one of the mock initializations, however, the sandbox doesn't allow that. The real fix will come next where we add those paths to the allow-list 

Risk Level: Low
Testing: See android_tests workflow
Docs Changes: N/A
Release Notes: N/A
Fixes #2020

### CODE REVIEW

**Comment by lfpino** [comment]
@jpsim could you please take a look?

**Review by jpsim — APPROVED** [review]
> The real fix will come next where we add those paths to the allow-list

Sounds right, looking forward to it.

---

These changes look good to me in the short term.

**Comment by jpsim** [comment]
@lfpino looks like the java_tests_mac job is repeatedly failing with the following errors:

```
/private/var/lib/engflow/worker/work/7/exec/bazel-out/darwin-fastbuild/bin/test/java/io/envoyproxy/envoymobile/engine/jvm_bridge_utility_test.runfiles/envoy_mobile/test/java/io/envoyproxy/envoymobile/engine/jvm_bridge_utility_test: line 260: fg: no job control
/private/var/lib/engflow/worker/work/7/exec/bazel-out/darwin-fastbuild/bin/test/java/io/envoyproxy/envoymobile/engine/jvm_bridge_utility_test.runfiles/envoy_mobile/test/java/io/envoyproxy/envoymobile/engine/jvm_bridge_utility_test: line 261: fg: no job control
/private/var/lib/engflow/worker/work/7/exec/bazel-out/darwin-fastbuild/bin/test/java/io/envoyproxy/envoymobile/engine/jvm_bridge_utility_test.runfiles/envoy_mobile/test/java/io/envoyproxy/envoymobile/engine/jvm_bridge_utility_test: line 262: fg: no job control
JUnit4 Test Runner
.....
Time: 0.139

OK (5 tests)


BazelTestRunner exiting with a return value of 0
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2022-02-28 16:26:10 --
```

**Comment by jpsim** [comment]
> If you see the flake again please open an issue and I'll investigate

will do

**Pull request merged**
