### PR TITLE
owners: add snowp to maintainers list

### PR DESCRIPTION
**Pull request by buildbreaker**
Signed-off-by: Alan Chiu <achiu@lyft.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description: owners: add snowp to maintainers list
Risk Level: n/a
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Review by snowp — APPROVED** [review]
Thanks!

**Review by alyssawilk — APPROVED** [review]
LGTM, though if @snowp has ideas more specific than general that'd be even better :-)

**Comment by buildbreaker** [comment]
happy to make those changes @snowp :)

**Comment by snowp** [comment]
Main thing I'd add would be `Envoy upstream`, if we want to get more detailed we could also include stuff like xDS and dataplane

**Review by goaway — APPROVED** [review]

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Pull request merged**
