### PR TITLE
update envoy submodule

### PR DESCRIPTION
**Pull request by snowp**
Signed-off-by: Snow Pettersen <snowp@lyft.com>

This brings in the yaml-cpp update which improves the error messaging for unknown anchors.
Risk Level: Medium
Testing: Existing tests
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by jingwei99** [comment]
note: pointed to the latest envoy mater for my local build, but had to remove these two lines: https://github.com/envoyproxy/envoy/pull/17467/files#diff-544556920c45b42cbfe40159b082ce8af6bd929e492d076769226265f215832fR82-R83

otherwise seeing error message: 
`ERROR: --host_action_env=PATH=/usr/bin:/bin:/opt/homebrew/bin:/usr/local/bin:/opt/local/bin :: Unrecognized option: --host_action_env=PATH=/usr/bin:/bin:/opt/homebrew/bin:/usr/local/bin:/opt/local/bin`

cc: @keith

**Comment by keith** [comment]
what version of bazel are you using? should be fine with the recent update https://github.com/envoyproxy/envoy-mobile/blob/main/.bazelversion

**Comment by jingwei99** [comment]
> what version of bazel are you using? should be fine with the recent update https://github.com/envoyproxy/envoy-mobile/blob/main/.bazelversion

3.6.0

ok that's why

**Comment by keith** [comment]
best to use bazelisk so it respects the version checked in here

**Comment by jingwei99** [comment]
> best to use bazelisk so it respects the version checked in here

im building with em-p pointing to latest master of envoy ... so it bypassed the .bazelrc in this repo ;)

**Comment by keith** [comment]
there is a symlink to this file in that repo as well, so I would think this should still apply

**Comment by jingwei99** [comment]
> there is a symlink to this file in that repo as well, so I would think this should still apply

umm.. the latest em has not been pulled to em-p yet, and for my set up, i basically bypassed the em updates, and directly pointed to envoy, anyway it's building for me
 
so in my em .bazelversion still points to 3.6.0, but the envoy submodule of that em is pointing to the latest main

**Comment by snowp** [comment]
@buildbreaker @goaway for review

**Review by jingwei99 — APPROVED** [review]
ahh, this would be helpful for the yaml debugging, would be nice to get it pulled to em-p

**Comment by goaway** [comment]
Thanks @snowp!

**Pull request merged**
