### PR TITLE
cleanup: consistently use nullptr in cc contexts

### PR DESCRIPTION
**Pull request by goaway**
Signed-off-by: Mike Schore <mike.schore@gmail.com>

### CODE REVIEW

**Review by jpsim — APPROVED** [review]
Is there no clang-tidy configuration for this?

**Comment by goaway** [comment]
> Is there no clang-tidy configuration for this?

Could be; probably worth looking into.

**Comment by goaway** [comment]
Thanks @jpsim!

**Comment by jpsim** [comment]
> Could be; probably worth looking into.

Looks like it: https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nullptr.html

**Comment by jpsim** [comment]
It not clear to me how to enable that in `.clang-format`

**Pull request merged**
