### PR TITLE
First pass at APIs for final stream metrics

### PR DESCRIPTION
**Pull request by alyssawilk**
This pass only sends up metrics onComplete.  TODO onError and onCancel

Description:
Risk Level:
Testing:
Part of #1520

### CODE REVIEW

**Review by junr03 — COMMENTED** [review]
At a high level this looks good, and in line with what would be useful to do some pretty comprehensive perf testing.

My main concern is about documenting the three different terms at play here:
stream info, stream intel, and stream metrics. I am afraid that future developers will be confused where to stick new information. 

As I see it, stream info is generally used in the context of Envoy's StreamInfo, StreamIntel is where we put information that is going to be useful on every callback, and stream metrics is where we put information that is only passed on stream termination. 

I know this is documented in the c_types and elsewhere but I wonder if we should be more explicit about it?

**Comment by alyssawilk** [comment]
Happy to be more explicit but do you have a suggestion of where we document
it? I'm not super familar with what goes where yet :-)

**Comment by goaway** [comment]
First of all, I think it's great to finally be exposing more of this via the API.

I had originally envisioned all of this simply going on StreamIntel. Totaled metrics would simply be in their final state on the last callback. Is a separate callback really necessary?

**Comment by alyssawilk** [comment]
ok, per discussion with @goaway I'm going to make this FinalStreamIntel and pass up onError / onComplete / onCancel

**Comment by goaway** [comment]
Thanks @alyssawilk this overall looks good. Thinking about it more though, final stream intel definitely will need the fields from the original stream intel one way or another - or we'll need to pass both structs on the terminal callbacks. This is because the final intel may be the only callback received for a stream (e.g. immediate cancellation or error).

Sorry to just now be thinking of this. :(

**Comment by alyssawilk** [comment]
ok, @goaway I think this is ready for another pass.

@carloseltuerto I'm going to ask your help debugging the early return I added.  I think it's a lifetime issue, where I made the upstreamInfo a shared pointer, so we didn't have to copy all the data all the time, but by the last up call to onComplete, the stats store is gone (which  IMO shouldn't go away until the envoy engine does?) so it gets cranky if you reference any stats.

Worst case we can copy all the time but I _think_ it's a test bug that the store is going away before the final completion call, I just don't understand lifetime issues in that test to be sure.

**Comment by goaway** [comment]
@alyssawilk feel free to copy/merge this in to fix kotlin formatting:

https://github.com/envoyproxy/envoy-mobile/pull/1952

There's a bazel target (`build kotlin_format_fix`) that _should_ work to fix kotlin formatting as well; unsure if it requires additional setup, but it runs locally just fine for me.

**Review by goaway — CHANGES_REQUESTED** [review]
This looks good to me, modulu formatting issues. @alyssawilk do you mind opening a tracking issue to update the iOS side of things for parity? I don't think it needs to be an immediate blocker, however.

**Review by goaway — APPROVED** [review]
Thanks @alyssawilk, looks great.

**Pull request merged**
