### PR TITLE
Update swift_flatbuffers to 2.0.8

### PR DESCRIPTION
**Pull request by jpsim**
Description: It now has a bazel build file for the Swift library so we can remove our own.
Risk Level: Low, we don't actually use this (for now), but it's used by the Lyft downstream integration.
Testing: CI
Docs Changes: N/A
Release Notes: N/A

Signed-off-by: JP Simard <jp@jpsim.com>

### CODE REVIEW

**Comment by jpsim** [comment]
We need to keep this in sync with Envoy's version: https://github.com/envoyproxy/envoy/blob/b08ca2e5831925f55611af2dd156c58ea27871b7/bazel/repository_locations.bzl#L1022

**Comment by jpsim** [comment]
Trying again with https://github.com/envoyproxy/envoy/pull/22998

**Review by RyanTheOptimist — COMMENTED** [review]
This seems to include Envoy change (or maybe an envoy import). Is that expected?

**Comment by jpsim** [comment]
> This seems to include Envoy change (or maybe an envoy import). Is that expected?

Yes, pulls in https://github.com/envoyproxy/envoy/pull/22998

**Comment by jpsim** [comment]
@goaway you were doing work with flat buffers recently, can you take a look?

**Review by Augustyniak — APPROVED** [review]

**Comment by goaway** [comment]
I'll confirm that this works on my flatbuffers branch, but at a glance I don't see anything concerning.

**Pull request merged**
