### PR TITLE
update envoy to 82b1f66

### PR DESCRIPTION
**Pull request by snowp**
Signed-off-by: Snow Pettersen <snowp@lyft.com>

Description:
Risk Level: Medium
Testing: n/a
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Review by jpsim — COMMENTED** [review]
Have you verified the reflection required for https://github.com/envoyproxy/envoy/pull/20169 is confirmed to work on iOS & Android? We use `allow_multiple_dns_addresses` for Happy Eyeballs which is one of the reloadable features we could check still works as expected.

Also, it looks like `IdleTimeoutTests` is crashing perhaps due to an uncaught exception.

**Comment by snowp** [comment]
I wouldn't expect there to be any platform specificity with that "reflection" since it's just reading the globally registered flags from absl instead of requiring a separate declaration (cc @alyssawilk). Is there an easy way to check that runtime value still work? Is there test coverage?

Re the ios test I think it's just a failing assertion, but the signal handler makes Envoy grab the ios exception and makes it look like a native one, looking into it

**Comment by snowp** [comment]
Yep removing Envoy signal handling I get 
```
2022-03-16 07:48:24.886 xctest[29833:6895281] *** Assertion failure in -[XCTestExpectation fulfill], XCTestExpectation.m:77
Invalid connection: com.apple.coresymbolicationd
2022-03-16 07:48:25.136 xctest[29833:6895281] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'API violation - multiple calls made to -[XCTestExpectation fulfill] for Str
eam idle timeout received by filter.'
*** First throw call stack:
(
        0   CoreFoundation                      0x000000010d169ba4 __exceptionPreprocess + 242
        1   libobjc.A.dylib                     0x000000010d01dbe7 objc_exception_throw + 48
        2   Foundation                          0x000000010db81aa2 _userInfoForFileAndLine + 0
        3   XCTestCore                          0x000000012592e97a -[XCTestExpectation fulfill] + 518
        4   test                                0x000000015143939a $s023test_swift_integration_A4_lib16IdleTimeoutTestsC0aeF0yyF0eF16ValidationFilterL_C7onError_11streamIntely5Envoy0nK0C_AI011FinalStreamM0CtF + 4
26
        5   test                                0x0000000151439628 $s023test_swift_integration_A4_lib16IdleTimeoutTestsC0aeF0yyF0eF16ValidationFilterL_C5Envoy08ResponseI0AagHP7onError_11streamIntelyAG0jM0C_AG011F
inalStreamO0CtFTW + 24
        6   test                                0x0000000151481305 $sSo15EnvoyHTTPFilterC0A0E6filterAbC6Filter_p_tcfcys6UInt64V_SSs5Int32VSo18envoy_stream_intelaSo0g7_final_h1_I0atcfU5_ + 549
        7   test                                0x0000000151482e92 $sSo15EnvoyHTTPFilterC0A0E6filterAbC6Filter_p_tcfcys6UInt64V_SSs5Int32VSo18envoy_stream_intelaSo0g7_final_h1_I0atcfU5_TA + 50
        8   test                                0x00000001514793a0 $ss6UInt64VSSs5Int32VSo18envoy_stream_intelaSo0c7_final_d1_E0aIegygyyy_ABSo8NSStringCAdfHIeyByyyyy_TR + 400
        9   test                                0x0000000152227d40 ios_http_filter_on_error + 416
```

We should probably disable this for ios tests

**Comment by snowp** [comment]
https://github.com/envoyproxy/envoy/commit/d7edf3bb7411296055171d0394280f9ef03b03fd this is the problematic change, it seems like changing what idle timeouts look like breaks our heuristic

**Comment by alyssawilk** [comment]
last time runtime screwed up we had a test fail so I think it'd detect that particular problem.  it'd probably be good to have explicit rather than implicit tests for it though!

**Review by junr03 — APPROVED** [review]

**Pull request merged**
